import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import "./custom.css";

import { Menu } from "@/components/custom/menu";
import { Footer } from "@/components/custom/footer";
import { loaders } from "@/app/data/loaders";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalResponse = await loaders.getGlobalData();
  const globalData = globalResponse.success ? globalResponse.data : null;

  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}>
        {globalData?.Menu && <Menu data={globalData.Menu} />}
        {children}
        {globalData?.Footer && <Footer data={globalData.Footer} />}
      </body>
    </html>
  );
}
